### ISSUE TITLE
compare traces of generated wasm variants

### ISSUE THREAD

**Issue by bbaudry** [KTH/slumps#31]
use the tracing feature of [SWAM](https://github.com/satabin/swam) to collect exec traces for each wasm variant and measure the runtime diversity

**Comment by monperrus** [comment]
Javier, what's the status of your PR on SWAM https://github.com/satabin/swam/pull/48?

**Comment by Jacarte** [comment]
Well, we have a first implementation of it with text-based traces. Now, I am waiting for the next iteration that Lucas [mentioned in SWAM](https://github.com/satabin/swam/pull/48#issuecomment-547474059) to extend to CTF format. Anyways, I need to check the code because is not passing the code quality stage 🤕

**Comment by Jacarte** [comment]
For now, to collect the traces, we need to use this [branch](https://github.com/Jacarte/swam/tree/feature/traces)

**Comment by satabin** [comment]
Hi there,

My big rewrite is almost done, I have a last weird bug to solve which is caused by changes in updated dependencies. The thing you can do now is to change the memory tracing by wrapping instances of Memory into a tracing one when the module is instantiated (see in the [`Instantiator`](https://github.com/satabin/swam/blob/master/runtime/src/swam/runtime/internals/instance/Instantiator.scala#L116) class.

**Comment by Jacarte** [comment]
> Hi there,
> 
> My big rewrite is almost done, I have a last weird bug to solve which is caused by changes in updated dependencies. The thing you can do now is to change the memory tracing by wrapping instances of Memory into a tracing one when the module is instantiated (see in the [`Instantiator`](https://github.com/satabin/swam/blob/master/runtime/src/swam/runtime/internals/instance/Instantiator.scala#L116) class.

Nice !! thanks @satabin

**Comment by Jacarte** [comment]
Done for [Rosseta56](https://github.com/KTH/slumps/releases/download/0.01/Rosseta56.zip), plot [here](https://github.com/KTH/slumps/blob/0.01/docs/imgs/variances.pdf).
